CREATE TABLE "CUSTOMER_INFO" 
   (	"CUSTID" VARCHAR2(6), 
	"FNAME" VARCHAR2(30), 
	"MNAME" VARCHAR2(30), 
	"LTNAME" VARCHAR2(30), 
	"CITY" VARCHAR2(15), 
	"MOBILENO" VARCHAR2(10), 
	"OCCUPATION" VARCHAR2(10), 
	"DOB" DATE, 
	 CONSTRAINT "CUST_CUSTID_PK" PRIMARY KEY ("CUSTID")
  USING INDEX  ENABLE
   ) ;

CREATE TABLE "BRANCH_INFO" 
   (	"BID" VARCHAR2(6), 
	"BNAME" VARCHAR2(30), 
	"BCITY" VARCHAR2(30), 
	 CONSTRAINT "BRANCH1_BID_PK" PRIMARY KEY ("BID")
  USING INDEX  ENABLE
   ) ;

CREATE TABLE "ACCOUNT_INFO" 
   (	"ACNUMBER" VARCHAR2(6), 
	"CUSTID" VARCHAR2(6), 
	"BID" VARCHAR2(6), 
	"OPENING_BALANCE" NUMBER(12,2), 
	"AOD" DATE, 
	"ATYPE" VARCHAR2(10), 
	"ASTATUS" VARCHAR2(10), 
	 CONSTRAINT "ACCOUNT_ACNUMBER1_PK" PRIMARY KEY ("ACNUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ACCOUNT_CUSTID1_FK" FOREIGN KEY ("CUSTID")
	  REFERENCES "CUSTOMER_INFO" ("CUSTID") ENABLE, 
	 CONSTRAINT "ACCOUNT_BID1_FK" FOREIGN KEY ("BID")
	  REFERENCES "BRANCH_INFO" ("BID") ENABLE
   ) ;
   
CREATE TABLE "TRANDETAILS_INFO" 
   (	"TNUMBER" VARCHAR2(6), 
	"ACNUMBER" VARCHAR2(6), 
	"DOT" DATE, 
	"MEDIUM_OF_TRANSACTION" VARCHAR2(20), 
	"TRANSACTION_TYPE" VARCHAR2(20), 
	"TRANSACTION_AMOUNT" NUMBER(12,2), 
	 CONSTRAINT "CHK_TTYPE" CHECK (transaction_type='Deposit' or transaction_type='Withdrawal') ENABLE, 
	 CONSTRAINT "TRANDETAILS_TNUMBER1_PK" PRIMARY KEY ("TNUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TRANDETAILS_ACNUMBER1_FK" FOREIGN KEY ("ACNUMBER")
	  REFERENCES "ACCOUNT_INFO" ("ACNUMBER") ENABLE
   ) ;
