  CREATE TABLE EMP 
   (	EMPID NUMERIC(8), 
	EMPNAME VARCHAR(40), 
	DOJ DATE, 
	AGE NUMERIC(3), 
	GENDER CHAR(1), 
	DEPTID NUMERIC(5), 
	SALARY NUMERIC(12,2), 
	MGR_ID NUMERIC(8), 
	 CONSTRAINT PK_EMPID_EMP PRIMARY KEY (EMPID));